apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: server-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-username/devops-prac-k8s.git # 실제 GitHub 저장소 URL로 변경해주세요
    targetRevision: HEAD
    path: charts/server/server
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
