apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-loki
  labels:
    app: {{ .Release.Name }}-loki
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-loki 