replicaCount: 1

image:
  repository: fluent/fluent-bit
  tag: 2.1.10
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 2020

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

# Fluent Bit 설정
config:
  service:
    flush: 1
    daemon: off
    log_level: info
    parsers_file: parsers.conf

  inputs:
    - name: tail
      tag: kube.*
      path: /var/log/pods/*/*/*/*.log
      parser: docker
      refresh_interval: 5
      mem_buf_limit: 5MB
      skip_long_lines: true

  filters:
    - name: kubernetes
      match: kube.*
      kube_url: https://kubernetes.default.svc:443
      kube_ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      kube_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kube_tag_prefix: kube.
      merge_log: true
      merge_log_key: log_processed
      k8s-logging.parser: on
      k8s-logging.exclude: on

  outputs:
    - name: stdout
      match: "*"
    # Loki 출력 설정 (Loki가 설치된 경우)
    - name: loki
      match: "*"
      host: loki-app
      port: 3100
      labels: job=fluentbit, k8s_namespace=$kubernetes['namespace_name'], k8s_pod_name=$kubernetes['pod_name'], k8s_container_name=$kubernetes['container_name']
      line_format: json
      tls: off

# 파서 설정
parsers:
  - name: docker
    format: json
    time_key: time
    time_format: "%Y-%m-%dT%H:%M:%S.%L%z"
