apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  labels:
    app: prometheus
    release: {{ .Release.Name }}
data:
  prometheus.yml: |-
    global:
      scrape_interval: {{ .Values.config.scrape_interval }}
      evaluation_interval: {{ .Values.config.evaluation_interval }}
    
    scrape_configs:
      {{- toYaml .Values.config.scrape_configs | nindent 6 }} 