apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
data:
  fluent-bit.conf: |
    [SERVICE]
      Flush {{ .Values.config.service.flush }}
      Daemon {{ .Values.config.service.daemon }}
      Log_Level {{ .Values.config.service.log_level }}
      Parsers_File parsers.conf

    {{- range .Values.config.inputs }}
    [INPUT]
      Name {{ .name }}
      Tag {{ .tag }}
      Path {{ .path }}
      Parser {{ .parser }}
      Refresh_Interval {{ .refresh_interval }}
      Mem_Buf_Limit {{ .mem_buf_limit }}
      Skip_Long_Lines {{ .skip_long_lines }}
      {{- if hasKey . "multiline.parser" }}
      Multiline.Parser {{ index . "multiline.parser" }}
      {{- end }}
    {{- end }}

    {{- range .Values.config.filters }}
    [FILTER]
      Name {{ .name }}
      Match {{ .match }}
      {{- if eq .name "kubernetes" }}
      Kube_URL {{ .kube_url }}
      Kube_CA_File {{ .kube_ca_file }}
      Kube_Token_File {{ .kube_token_file }}
      Kube_Tag_Prefix {{ .kube_tag_prefix }}
      Merge_Log {{ .merge_log }}
      Merge_Log_Key {{ .merge_log_key }}
      {{- if hasKey . "k8s-logging.parser" }}
      K8S-Logging.Parser {{ index . "k8s-logging.parser" }}
      {{- end }}
      {{- if hasKey . "k8s-logging.exclude" }}
      K8S-Logging.Exclude {{ index . "k8s-logging.exclude" }}
      {{- end }}
      {{- else if eq .name "parser" }}
      Key_Name {{ .key_name }}
      Parser {{ .parser }}
      Reserve_Data {{ .reserve_data }}
      {{- else if eq .name "modify" }}
      Condition {{ .condition }}
      Copy {{ .copy }}
      {{- end }}
    {{- end }}

    {{- range .Values.config.outputs }}
    [OUTPUT]
      Name {{ .name }}
      Match {{ .match }}
      {{- if eq .name "loki" }}
      Host {{ .host }}
      Port {{ .port }}
      Labels {{ .labels }}
      Line_Format {{ .line_format }}
      TLS {{ .tls }}
      Auto_Kubernetes_Labels {{ .auto_kubernetes_labels }}
      {{- if .remove_keys }}
      Remove_Keys {{ .remove_keys }}
      {{- end }}
      {{- end }}
    {{- end }}

  parsers.conf: |
    {{- range .Values.parsers }}
    [PARSER]
      Name {{ .name }}
      {{- if hasKey . "type" }}
      Type {{ .type }}
      Flush_Timeout {{ .flush_timeout }}
      {{- else }}
      Format {{ .format }}
      {{- if eq .format "regex" }}
      Regex {{ .regex }}
      {{- end }}
      Time_Key {{ .time_key }}
      Time_Format {{ .time_format }}
      {{- end }}
      
      {{- if hasKey . "rule" }}
      # 멀티라인 파싱 규칙
      Rule {{ .rule }}
      {{- range .rules }}
      Rule_{{ .state }} {{ .regex }} {{ .next }}
      {{- end }}
      {{- end }}
    {{- end }}