apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-promtail
  labels:
    app: {{ .Release.Name }}-promtail
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-promtail
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-promtail
  apiGroup: rbac.authorization.k8s.io 