apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentbit-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/junho100/devops-prac-k8s.git
    targetRevision: HEAD
    path: charts/fluentbit
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
